# Generated by Django 3.2.5 on 2021-07-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0004_auto_20210712_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='static/uploads')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Invent.items')),
            ],
        ),
    ]
